//! The hand-written edge-case corpus, shared by `probe` and `gen_corpus`.

#[allow(clippy::vec_init_then_push)]
pub fn cases() -> Vec<(&'static str, String)> {
    vec![
        ("strand repro: folded with em dash", "status: >\n  v2 — x\nbeads: y\n".into()),
        ("literal with em dash, two in a row", "a: |\n  é—ü\n  second\nb: |\n  ✓✓\nc: y\n".into()),
        ("literal, long non-ascii line > 16 chars", format!("a: |\n  {}\nb: y\n", "é".repeat(40))),
        ("plain non-ascii then key", "a: héllo ✓\nb: y\n".into()),
        ("double-quoted non-ascii then key", "a: \"héllo ✓\"\nb: y\n".into()),
        ("single-quoted with doubled quote", "a: 'it''s'\nb: y\n".into()),
        ("double-quoted escapes", "a: \"x\\ty\\n\\u00e9\\\"\"\nb: y\n".into()),
        ("comment with non-ascii then key", "a: 1 # héllo ✓ comment\nb: y\n".into()),
        ("comment-only line with non-ascii", "# ✓✓✓\na: 1\nb: y\n".into()),
        ("block mapping nested", "p:\n  t: x\n  l:\n    - a\n    - b\nq: 1\n".into()),
        ("flow collections", "a: [1, 2, {k: v}]\nb: {x: [y]}\n".into()),
        ("empty values", "a:\nb: ~\nc: ''\nd:\n  - \n  - x\n".into()),
        ("tags and anchors", "a: !expr x + 1\nb: !!str 5\nc: &anc !t [1]\nd: *anc\ne: !<tag:yaml.org,2002:int> 7\n".into()),
        ("tag on block mapping", "!t\na: 1\nb: 2\n".into()),
        ("tag on block seq", "k: !t\n  - a\n  - b\n".into()),
        ("quoted keys and multi-line plain", "\"k\": a\n  b\n\n  c\n'j': 2\n".into()),
        ("multi-line double quoted", "a: \"x\n  y\"\nb: 1\n".into()),
        ("crlf", "a: |\r\n  x\r\nb: y\r\n".into()),
        ("block scalar keep/strip, trailing blanks", "a: |+\n  x\n\n\nb: |-\n  y\nc: z\n".into()),
        ("empty block scalar", "a: |\nb: y\n".into()),
        ("explicit doc markers", "---\na: 1\n...\n".into()),
        ("root scalar", "hello".into()),
        ("empty input", "".into()),
        ("tab in block literal", "a: |\n  x\ty\nb: 1\n".into()),
        ("indentless sequence", "a:\n- x\n- y\nb: 1\n".into()),
        ("more-indented folded", "a: >\n  x\n    y\n  z\nb: 1\n".into()),
        ("ERR unclosed flow seq", "title: x\nauthor: [a, b\nformat: html\n".into()),
        ("ERR unclosed flow seq non-ascii before", "title: \"héllo ✓\"\nauthor: [a, b\nformat: html\n".into()),
        ("ERR eof in flow seq", "title: x\nauthor: [a, b".into()),
        ("ERR bad indentation", "a:\n  b: 1\n c: 2\n".into()),
        ("ERR unknown anchor", "a: *nope\n".into()),
        ("ERR duplicate-ish: mapping values not allowed", "a: b: c\n".into()),
        ("ERR tab indentation", "a:\n\tb: 1\n".into()),
        ("ERR unclosed quote", "a: \"x\nb: 1\n".into()),
        ("empty block scalar at EOF no newline", "a: |".into()),
        ("empty block scalar at EOF with newline", "a: |\n".into()),
        ("empty block scalar then blank line EOF", "a: |\n\n".into()),
        ("blank-only folded then key", "a: >\n  \nb: 1\n".into()),
        ("empty literal, next key indented less", "k:\n  a: |\nj: 1\n".into()),
        ("empty value at EOF", "a:".into()),
        ("empty value mid-map then nested", "a:\nb:\n  c: 1\n".into()),
        ("saphyr span.rs nested seq in seq item", "foo:\n  - a\n  - bar:\n    - b\n    - c".into()),
        ("mapping inside seq item", "- a: 1\n  b: 2\n- c\n".into()),
        ("complex key", "? [a, b]\n: v\nk: 1\n".into()),
        ("non-ascii anchor and tag names", "a: &ñ !é x\nb: *ñ\nc: 1\n".into()),
        ("single-quoted non-ascii doubled quote then key", "a: 'é''ü'\nb: y\n".into()),
        ("more-indented non-ascii in literal then key", "a: |\n  x\n    éé\n  y\nb: 1\n".into()),
        ("block scalar with indentation indicator", "a: |2\n   x\nb: 1\n".into()),
        ("block scalar followed by comment lines", "a: |\n  x\n# c\n\nb: 1\n".into()),
        ("plain scalar with hash no space", "a: x#y\nb: 1\n".into()),
        ("multi document", "a: 1\n---\nb: 2\n".into()),
        ("anchor on block mapping", "&m\na: 1\n".into()),
        ("empty flow collections", "a: []\nb: {}\nc: 1\n".into()),
        ("trailing comment after block map", "a: 1\n# end\n".into()),
        ("only whitespace", "  \n\n".into()),
        ("only comment", "# nothing\n".into()),
        ("ERR duplicate anchor ok? / bad flow key", "a: {b c}\n".into()),
        ("ERR tag handle undeclared", "a: !x!y z\n".into()),
        ("ERR block seq in map value wrong indent", "a: 1\n- b\n".into()),
        ("ERR comment intercepts plain", "a: x\n# c\n  y\n".into()),
    ]
}
