//! Failing tests for scalar content provenance (Phase 2 of
//! `claude-notes/plans/2026-08-20-provenance-1-foundations.md` in the q2
//! repo). Every test here transcribes a row from
//! `claude-notes/research/2026-08-21-yaml-content-provenance-fixtures.md`
//! and must be **RED** as of this commit: `content_source_info()` is `None`
//! for every scalar until the next task teaches the parser to derive and
//! attach it (see `YamlWithSourceInfo::content_source_info`'s doc comment
//! and the stub commit that introduced it).
//!
//! Per the fixtures note, do not re-derive expected values by hand — that
//! risks encoding this author's reading of YAML's folding rules instead of
//! the behavior the lockstep walker actually produces. Every expected piece
//! list below is transcribed from the note, which was generated by running
//! `claude-notes/research/yaml-content-provenance-walker/walker.rs` against
//! this crate and is itself the plan's stated authority for Phase 2.
//!
//! We assert the piece list (`SourceInfo::Original`/`SourceInfo::Concat`
//! and its `SourcePiece`s), not `map_offset` — this crate has no `tests/`
//! directory and constructs a `SourceContext` nowhere in `src/`, so routing
//! every fixture through `map_offset` would need an unbudgeted helper. A
//! `SourcePiece`'s fields are public and match the note's `content <-
//! source` notation directly. Two `map_offset` tests near the bottom cover
//! that contract instead.

use crate::parse;
use quarto_source_map::{FileId, SourceContext, SourceInfo};

/// The expected `SourceInfo` for a scalar whose derivation collapsed to a
/// single byte-identical run over `source[start..end]` — what
/// `ProvenanceBuilder::finish()` (quarto-source-map) emits for an all-file
/// scalar with exactly one *verbatim* piece, or none at all (the anchor
/// case: `finish()` on an empty piece list returns a zero-length `Original`
/// at the anchor, not `None` — see the fixtures note, "Provenance is
/// `Option`, and 'empty' is not `None`").
fn contiguous(start: usize, end: usize) -> SourceInfo {
    SourceInfo::original(FileId(0), start, end)
}

/// The expected `SourceInfo::Concat` for a scalar whose derivation produced
/// more than one piece, or exactly one piece that is a *replacement* (which
/// must not collapse to `contiguous` — see `single_quoted_all_escape`
/// below). `pieces` is `(content_range, source_range)` per piece, matching
/// the fixtures note's `content <- source` notation; `SourceInfo::concat`
/// computes each piece's `offset_in_concat` from the content ranges' order
/// and length, so passing the content range's length is enough.
fn concat(pieces: &[(std::ops::Range<usize>, std::ops::Range<usize>)]) -> SourceInfo {
    SourceInfo::concat(
        pieces
            .iter()
            .map(|(content, source)| (contiguous(source.start, source.end), content.len()))
            .collect(),
    )
}

// ---------------------------------------------------------------------
// block `|`
// ---------------------------------------------------------------------

#[test]
fn block_pipe_single_line() {
    let src = "k: |\n  aaa\n";
    let yaml = parse(src).unwrap();
    let v = yaml.get_hash_value("k").unwrap();
    assert_eq!(v.content_source_info(), Some(&contiguous(7, 11)));
}

#[test]
fn block_pipe_three_lines() {
    let src = "k: |\n  aaa\n  bbb\n  ccc\n";
    let yaml = parse(src).unwrap();
    let v = yaml.get_hash_value("k").unwrap();
    let expected = concat(&[
        (0..3, 7..10),
        (3..4, 10..13),
        (4..7, 13..16),
        (7..8, 16..19),
        (8..12, 19..23),
    ]);
    assert_eq!(v.content_source_info(), Some(&expected));
}

#[test]
fn block_pipe_no_final_newline() {
    let src = "k: |\n  aaa";
    let yaml = parse(src).unwrap();
    let v = yaml.get_hash_value("k").unwrap();
    // The trailing piece is synthesis: a chomped final newline with no
    // source byte (a zero-width source range, non-zero content length).
    let expected = concat(&[(0..3, 7..10), (3..4, 10..10)]);
    assert_eq!(v.content_source_info(), Some(&expected));
}

#[test]
fn block_pipe_strip() {
    // `|-`
    let src = "k: |-\n  aaa\n  bbb\n";
    let yaml = parse(src).unwrap();
    let v = yaml.get_hash_value("k").unwrap();
    let expected = concat(&[(0..3, 8..11), (3..4, 11..14), (4..7, 14..17)]);
    assert_eq!(v.content_source_info(), Some(&expected));
}

#[test]
fn block_pipe_keep() {
    // `|+`
    let src = "k: |+\n  aaa\n\n\n";
    let yaml = parse(src).unwrap();
    let v = yaml.get_hash_value("k").unwrap();
    assert_eq!(v.content_source_info(), Some(&contiguous(8, 14)));
}

#[test]
fn block_pipe_blank_line_inside() {
    let src = "k: |\n  aaa\n\n  bbb\n";
    let yaml = parse(src).unwrap();
    let v = yaml.get_hash_value("k").unwrap();
    let expected = concat(&[(0..3, 7..10), (3..5, 10..14), (5..9, 14..18)]);
    assert_eq!(v.content_source_info(), Some(&expected));
}

#[test]
fn block_pipe_more_indented_line() {
    let src = "k: |\n  aaa\n    bbb\n  ccc\n";
    let yaml = parse(src).unwrap();
    let v = yaml.get_hash_value("k").unwrap();
    let expected = concat(&[
        (0..3, 7..10),
        (3..4, 10..13),
        (4..9, 13..18),
        (9..10, 18..21),
        (10..14, 21..25),
    ]);
    assert_eq!(v.content_source_info(), Some(&expected));
}

#[test]
fn block_pipe2_indentation_indicator() {
    let src = "k: |2\n    aaa\n    bbb\n";
    let yaml = parse(src).unwrap();
    let v = yaml.get_hash_value("k").unwrap();
    let expected = concat(&[(0..5, 8..13), (5..6, 13..16), (6..12, 16..22)]);
    assert_eq!(v.content_source_info(), Some(&expected));
}

#[test]
fn block_pipe_trailing_spaces_last_line() {
    let src = "k: |\n  aaa\n  bbb   \n";
    let yaml = parse(src).unwrap();
    let v = yaml.get_hash_value("k").unwrap();
    let expected = concat(&[(0..3, 7..10), (3..4, 10..13), (4..11, 13..20)]);
    assert_eq!(v.content_source_info(), Some(&expected));
}

#[test]
fn block_pipe_crlf() {
    let src = "k: |\r\n  aaa\r\n  bbb\r\n";
    let yaml = parse(src).unwrap();
    let v = yaml.get_hash_value("k").unwrap();
    // The `\r` is absorbed into the break replacement, not a separate
    // deletion.
    let expected = concat(&[
        (0..3, 8..11),
        (3..4, 11..15),
        (4..7, 15..18),
        (7..8, 18..20),
    ]);
    assert_eq!(v.content_source_info(), Some(&expected));
}

#[test]
fn block_pipe_tab_in_content() {
    let src = "k: |\n  a\tb\n";
    let yaml = parse(src).unwrap();
    let v = yaml.get_hash_value("k").unwrap();
    assert_eq!(v.content_source_info(), Some(&contiguous(7, 11)));
}

#[test]
fn block_pipe_content_starts_with_pipe() {
    // The header-skip predicate must NOT fire here: the decoded value is
    // not empty/all-newlines, so this derives normally.
    let src = "k: |\n  |pipe\n";
    let yaml = parse(src).unwrap();
    let v = yaml.get_hash_value("k").unwrap();
    assert_eq!(v.content_source_info(), Some(&contiguous(7, 13)));
}

#[test]
fn block_pipe_content_is_exactly_pipe() {
    let src = "k: |\n  |\n";
    let yaml = parse(src).unwrap();
    let v = yaml.get_hash_value("k").unwrap();
    assert_eq!(v.content_source_info(), Some(&contiguous(7, 9)));
}

#[test]
fn block_fold_blank_line() {
    // `>`
    let src = "k: >\n  aaa\n  bbb\n\n  ccc\n";
    let yaml = parse(src).unwrap();
    let v = yaml.get_hash_value("k").unwrap();
    let expected = concat(&[
        (0..3, 7..10),
        (3..4, 10..13),
        (4..7, 13..16),
        (7..8, 16..20),
        (8..12, 20..24),
    ]);
    assert_eq!(v.content_source_info(), Some(&expected));
}

#[test]
fn block_fold_more_indented_not_folded() {
    let src = "k: >\n  aaa\n    bbb\n";
    let yaml = parse(src).unwrap();
    let v = yaml.get_hash_value("k").unwrap();
    let expected = concat(&[(0..3, 7..10), (3..4, 10..13), (4..10, 13..19)]);
    assert_eq!(v.content_source_info(), Some(&expected));
}

// ---------------------------------------------------------------------
// plain
// ---------------------------------------------------------------------

#[test]
fn plain_single_line() {
    let src = "k: hello\n";
    let yaml = parse(src).unwrap();
    let v = yaml.get_hash_value("k").unwrap();
    assert_eq!(v.content_source_info(), Some(&contiguous(3, 8)));
}

#[test]
fn plain_multi_line() {
    let src = "k: aaa\n  bbb\n  ccc\n";
    let yaml = parse(src).unwrap();
    let v = yaml.get_hash_value("k").unwrap();
    let expected = concat(&[
        (0..3, 3..6),
        (3..4, 6..9),
        (4..7, 9..12),
        (7..8, 12..15),
        (8..11, 15..18),
    ]);
    assert_eq!(v.content_source_info(), Some(&expected));
}

#[test]
fn plain_multi_line_crlf() {
    let src = "k: aaa\r\n  bbb\r\n";
    let yaml = parse(src).unwrap();
    let v = yaml.get_hash_value("k").unwrap();
    let expected = concat(&[(0..3, 3..6), (3..4, 6..10), (4..7, 10..13)]);
    assert_eq!(v.content_source_info(), Some(&expected));
}

// ---------------------------------------------------------------------
// single-quoted
// ---------------------------------------------------------------------

#[test]
fn single_quoted() {
    let src = "k: 'hello'\n";
    let yaml = parse(src).unwrap();
    let v = yaml.get_hash_value("k").unwrap();
    assert_eq!(v.content_source_info(), Some(&contiguous(4, 9)));
}

#[test]
fn single_quoted_with_doubled_quote() {
    let src = "k: 'it''s'\n";
    let yaml = parse(src).unwrap();
    let v = yaml.get_hash_value("k").unwrap();
    let expected = concat(&[(0..2, 4..6), (2..3, 6..8), (3..4, 8..9)]);
    assert_eq!(v.content_source_info(), Some(&expected));
}

#[test]
fn single_quoted_trailing_doubled_quote() {
    let src = "k: 'its'''\n";
    let yaml = parse(src).unwrap();
    let v = yaml.get_hash_value("k").unwrap();
    let expected = concat(&[(0..3, 4..7), (3..4, 7..9)]);
    assert_eq!(v.content_source_info(), Some(&expected));
}

#[test]
fn single_quoted_all_escape() {
    // `k: ''''` — one replacement piece (2 source bytes -> 1 content byte).
    // Must stay a 1-piece Concat, never collapse to `contiguous`: a
    // contiguous `Original` here would claim a byte-identical source range
    // this piece doesn't have, breaking the length invariant.
    let src = "k: ''''\n";
    let yaml = parse(src).unwrap();
    let v = yaml.get_hash_value("k").unwrap();
    let expected = concat(&[(0..1, 4..6)]);
    assert_eq!(v.content_source_info(), Some(&expected));
    assert!(
        !matches!(v.content_source_info(), Some(SourceInfo::Original { .. })),
        "a single replacement piece must not collapse to a contiguous SourceInfo"
    );
}

// ---------------------------------------------------------------------
// double-quoted
// ---------------------------------------------------------------------

#[test]
fn double_quoted_plain() {
    // No escapes — every other double-quoted fixture has at least one.
    let src = "k: \"hello\"\n";
    let yaml = parse(src).unwrap();
    let v = yaml.get_hash_value("k").unwrap();
    assert_eq!(v.content_source_info(), Some(&contiguous(4, 9)));
}

#[test]
fn double_quoted_tab_escape() {
    let src = "k: \"a\\tb\"\n";
    let yaml = parse(src).unwrap();
    let v = yaml.get_hash_value("k").unwrap();
    let expected = concat(&[(0..1, 4..5), (1..2, 5..7), (2..3, 7..8)]);
    assert_eq!(v.content_source_info(), Some(&expected));
}

#[test]
fn double_quoted_newline_escape() {
    let src = "k: \"a\\nb\"\n";
    let yaml = parse(src).unwrap();
    let v = yaml.get_hash_value("k").unwrap();
    let expected = concat(&[(0..1, 4..5), (1..2, 5..7), (2..3, 7..8)]);
    assert_eq!(v.content_source_info(), Some(&expected));
}

#[test]
fn double_quoted_unicode_escape() {
    let src = "k: \"a\\u00e9b\"\n";
    let yaml = parse(src).unwrap();
    let v = yaml.get_hash_value("k").unwrap();
    let expected = concat(&[(0..1, 4..5), (1..3, 5..11), (3..4, 11..12)]);
    assert_eq!(v.content_source_info(), Some(&expected));
}

#[test]
fn double_quoted_many_escapes() {
    let src = "k: \"a\\\\b\\\"c\\td\"\n";
    let yaml = parse(src).unwrap();
    let v = yaml.get_hash_value("k").unwrap();
    let expected = concat(&[
        (0..1, 4..5),
        (1..2, 5..7),
        (2..3, 7..8),
        (3..4, 8..10),
        (4..5, 10..11),
        (5..6, 11..13),
        (6..7, 13..14),
    ]);
    assert_eq!(v.content_source_info(), Some(&expected));
}

#[test]
fn double_quoted_multiline_fold() {
    let src = "k: \"hello\n  world\"\n";
    let yaml = parse(src).unwrap();
    let v = yaml.get_hash_value("k").unwrap();
    let expected = concat(&[(0..5, 4..9), (5..6, 9..12), (6..11, 12..17)]);
    assert_eq!(v.content_source_info(), Some(&expected));
}

#[test]
fn double_quoted_escaped_break() {
    // `\` + newline. The middle piece has zero content length (a deletion)
    // but is stored, not dropped, so the piece list tiles its source
    // contiguously.
    let src = "k: \"aaa\\\n  bbb\"\n";
    let yaml = parse(src).unwrap();
    let v = yaml.get_hash_value("k").unwrap();
    let expected = concat(&[(0..3, 4..7), (3..3, 7..11), (3..6, 11..14)]);
    assert_eq!(v.content_source_info(), Some(&expected));
}

// ---------------------------------------------------------------------
// root scalar — the byte-identity binding case
// ---------------------------------------------------------------------

#[test]
fn root_plain_col0_continuation() {
    // "aaa\nbbb\n" as a root-level plain scalar decodes to "aaa bbb": a
    // 1-byte fold whose source run (`\n`) and content (` `) are the same
    // *length* but not the same *bytes*. This is the only fixture that
    // binds the verbatim tag to byte-identity rather than length: every
    // other row's break region happens to be a byte-identical newline run,
    // so a buggy length-only rule would pass every other test here while
    // wrongly collapsing this one to a contiguous `Original(0, 7)`.
    let src = "aaa\nbbb\n";
    let yaml = parse(src).unwrap();
    let expected = concat(&[(0..3, 0..3), (3..4, 3..4), (4..7, 4..7)]);
    assert_eq!(yaml.content_source_info(), Some(&expected));
}

// ---------------------------------------------------------------------
// empty and degenerate scalars — `Some` of a zero-length `SourceInfo`,
// never `None`. "Empty but derived" must be distinguishable from "could
// not derive".
// ---------------------------------------------------------------------

#[test]
fn empty_value() {
    let src = "k:\n";
    let yaml = parse(src).unwrap();
    let v = yaml.get_hash_value("k").unwrap();
    assert_eq!(v.content_source_info(), Some(&contiguous(3, 3)));
}

#[test]
fn empty_single_quoted() {
    let src = "k: ''\n";
    let yaml = parse(src).unwrap();
    let v = yaml.get_hash_value("k").unwrap();
    // Anchor is the value's span start (quote included), not the first
    // content byte — there is no content byte.
    assert_eq!(v.content_source_info(), Some(&contiguous(3, 3)));
}

#[test]
fn empty_block_scalar() {
    // `k: |` alone. Works via the header-skip rule: the span covers the `|`
    // header rather than any content, so the walk starts at the newline
    // ending the header line, producing one verbatim piece that collapses
    // to a contiguous `SourceInfo` over that single newline byte.
    let src = "k: |\n";
    let yaml = parse(src).unwrap();
    let v = yaml.get_hash_value("k").unwrap();
    assert_eq!(v.content_source_info(), Some(&contiguous(4, 5)));
}

// ---------------------------------------------------------------------
// scalar position: keys, flow-collection items, tagged scalars
// ---------------------------------------------------------------------

#[test]
fn quoted_key() {
    // `key_span` has the identical defect as `value_span` (it includes the
    // quotes), so a key's content provenance must derive the same way as
    // a value's.
    let src = "'quoted key': v\n";
    let yaml = parse(src).unwrap();
    let entries = yaml.as_hash().unwrap();
    assert_eq!(
        entries[0].key.content_source_info(),
        Some(&contiguous(1, 11))
    );
}

#[test]
fn flow_collection_item_0() {
    let src = "k: ['a b', \"c\\td\"]\n";
    let yaml = parse(src).unwrap();
    let v = yaml.get_hash_value("k").unwrap();
    let items = v.as_array().unwrap();
    assert_eq!(items[0].content_source_info(), Some(&contiguous(5, 8)));
}

#[test]
fn flow_collection_item_1() {
    let src = "k: ['a b', \"c\\td\"]\n";
    let yaml = parse(src).unwrap();
    let v = yaml.get_hash_value("k").unwrap();
    let items = v.as_array().unwrap();
    let expected = concat(&[(0..1, 12..13), (1..2, 13..15), (2..3, 15..16)]);
    assert_eq!(items[1].content_source_info(), Some(&expected));
}

#[test]
fn tagged_scalar() {
    // The node marker points at the VALUE, not the tag (`k: !path 'x/y'`
    // gives span 9..14 = `'x/y'`), so tags need no extra arithmetic.
    let src = "k: !path 'x'\n";
    let yaml = parse(src).unwrap();
    let v = yaml.get_hash_value("k").unwrap();
    assert_eq!(v.content_source_info(), Some(&contiguous(10, 11)));
}

// ---------------------------------------------------------------------
// non-string scalars: content is the event's value string, not `self.yaml`
// ---------------------------------------------------------------------

#[test]
fn null_scalar() {
    let src = "k: ~\n";
    let yaml = parse(src).unwrap();
    let v = yaml.get_hash_value("k").unwrap();
    assert_eq!(v.content_source_info(), Some(&contiguous(3, 4)));
}

#[test]
fn boolean_scalar() {
    let src = "k: true\n";
    let yaml = parse(src).unwrap();
    let v = yaml.get_hash_value("k").unwrap();
    assert_eq!(v.content_source_info(), Some(&contiguous(3, 7)));
}

// ---------------------------------------------------------------------
// map_offset contract (kept minimal — the piece-list assertions above are
// the load-bearing tests; these three exercise `map_offset` itself)
// ---------------------------------------------------------------------

fn context_for(src: &str) -> SourceContext {
    let mut ctx = SourceContext::new();
    ctx.add_file("test.yaml".to_string(), Some(src.to_string()));
    ctx
}

#[test]
fn map_offset_contiguous_scalar() {
    let src = "k: 'hello'\n";
    let yaml = parse(src).unwrap();
    let v = yaml.get_hash_value("k").unwrap();
    let ctx = context_for(src);
    let si = v
        .content_source_info()
        .expect("derivation must produce Some");
    // Content offset 2 (the second 'l') is source offset 4 + 2 = 6.
    let mapped = si
        .map_offset(2, &ctx)
        .expect("offset within content must map");
    assert_eq!(mapped.location.offset, 6);
}

#[test]
fn map_offset_into_replacement_piece() {
    let src = "k: \"a\\tb\"\n";
    let yaml = parse(src).unwrap();
    let v = yaml.get_hash_value("k").unwrap();
    let ctx = context_for(src);
    let si = v
        .content_source_info()
        .expect("derivation must produce Some");
    // Content offset 1 (the decoded '\t') is inside the replacement piece
    // `1..2 <- 5..7`; per the contract, an offset inside a collapsed
    // region resolves to the start of that region: source offset 5.
    let mapped = si
        .map_offset(1, &ctx)
        .expect("offset within a replacement piece must map");
    assert_eq!(mapped.location.offset, 5);
}

#[test]
fn map_offset_at_content_end() {
    let src = "k: \"a\\tb\"\n";
    let yaml = parse(src).unwrap();
    let v = yaml.get_hash_value("k").unwrap();
    let ctx = context_for(src);
    let si = v
        .content_source_info()
        .expect("derivation must produce Some");
    // The exclusive end of the content (offset 3, the length of "a\tb")
    // maps like `Original`/`Substring`'s `map_offset(length)`: to the end
    // of the last piece, source offset 8.
    let mapped = si
        .map_offset(3, &ctx)
        .expect("offset at content end must map");
    assert_eq!(mapped.location.offset, 8);
}
